# Generated by Django 2.2.1 on 2019-06-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschema',
            name='city_name',
        ),
    ]
