# Generated by Django 2.2.1 on 2019-06-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_dataschema_city_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSchema',
        ),
    ]
