# Generated by Django 2.2.1 on 2019-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dataschema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSchema',
        ),
    ]
