# Generated by Django 2.2.1 on 2019-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190610_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_gen', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city', models.CharField(max_length=100)),
                ('company_state', models.CharField(max_length=100)),
                ('company_country', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=100)),
                ('company_linkedin', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('owner_linkedin', models.CharField(max_length=100)),
                ('owner_title', models.CharField(max_length=100)),
                ('owner_twitter', models.CharField(max_length=100)),
            ],
        ),
    ]
