# Generated by Django 2.2.2 on 2019-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='company_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='f_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
    ]
