# Generated by Django 2.2.2 on 2019-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190618_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='company_url',
            field=models.CharField(max_length=200),
        ),
    ]
