# Generated by Django 2.2.2 on 2019-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190618_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='company_email',
            field=models.EmailField(max_length=200),
        ),
    ]
